### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by alex0n** [BruceJillis/PHP-Language-Detection#1]
Hi!
Is it possible to add some addigional language support to your "PHP Language Detection" project?
What should be done to do that? As I understand we need to create n-gram profiles for each language,right? If so, how to do that? Thanks

**Comment by BruceJillis** [comment]
Hej Alex! 

Jeah adding languages is definitely possible, you only need to supply a (balanced) amount of text in that new language and then create a new model using it: just scrape together an amount of text in the language you want to add that is roughly equal in size to the other language files (etc/data/*.raw), edit build.php to include the new data (add a $classifier->train(...) line) and then simply run it. This will create a new model file should support the new language as well as the old.
