### ISSUE TITLE
Ukrainian support

### ISSUE THREAD

**Issue by podarok** [BruceJillis/PHP-Language-Detection#3]
Hello
Thanks for the great work.

I want to ask you, did you have a chance to test this code for other languages, like Ukraininan or Belarusian?
If no, I'd like to ask you how-to create *.raw files and source data files for ability to use this code for languages above?

**Comment by BruceJillis** [comment]
Thank you! Yes, the library should support any language encodable in unicode. As I am currently searching for a new job I will not be doing any work on the library. There is nothing special about the raw files, they are just text files with string from the language you wish to detect. The files should have the right encoding (unicode) but that's about it. I created them using chrome, copy-and-paste and a text editor (wikipedia has really good text, I recall getting a lot of the supplied raw files from there).

**Comment by podarok** [comment]
thanks a lot. I'll try to extend it.
